name: Build

on: [push, pull_request]

jobs:
  build_sdist:
    name: Build sdist on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: pipx run build --sdist -o dist
      - uses: actions/upload-artifact@v4
        with:
          name: dist-source
          path: ./dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: build_sdist
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: pypa/cibuildwheel@v2.17.0
        with:
          output-dir: dist
      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: ./dist/*.whl
  
  merge:
    name: Merge Artifacts
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: dist
          delete-merged: true
